Repository dnsimple/dnsimple-support, pull requests merged in 2018-10, with the labels that each got.

#359 UK domains may or may not be extended depending on expiration date
  content/articles/transferring-uk-domain.markdown
Labels: enhancement, ready-for-review

#361 Removes old account page overview
  content/articles/new-account-page.markdown
Labels: ready-for-review

#356 Auto-import DNS records article
  content/articles/auto-import-dns.markdown
  content/files/auto-import-dns-conflict.png
  content/files/auto-import-dns-overview.png
Labels: articles, ready-for-review

#365 DNSimple Services edits
  content/articles/dnsimple-services.markdown
Labels: copy editing, ready-for-review

#366 Support and Status edits
  content/articles/dnsimple-status.markdown
  content/articles/dnsimple-support.markdown
Labels: copy editing, ready-for-review

#369 Web host why register edits
  content/articles/drop-catching.markdown
  content/articles/email-hosting.markdown
  content/articles/reasons-registering-domain.markdown
  content/articles/web-hosting.markdown
Labels: copy editing, ready-for-review

#370 Expiring product edits
  content/articles/expiring-product-email-notifications.markdown
Labels: copy editing, ready-for-review
