Repository dnsimple/dnsimple-support, pull requests merged in 2018-12, with the labels that each got.

#396 Updates screenshots for user pages
  content/articles/account-multi.markdown
  content/articles/account-subscription-balance.markdown
  content/articles/changing-user-email.markdown
  content/files/account-change-email-3.jpg
  content/files/add-new-account-link.jpg
  content/files/add-new-account-link.png
  content/files/user-2fa-disable-link.png
  content/files/user-2fa-enable-link.png
  content/files/user-account-selection.jpg
  content/files/user-email.png
Labels: ready-for-review

#392 New plans copy edits
  content/articles/new-plans-for-bronze.markdown
  content/articles/new-plans-for-gold.markdown
  content/articles/new-plans-for-silver.markdown
  content/articles/new-plans.markdown
Labels: copy editing

#395 Subscription edits
  content/articles/cancel-subscription.markdown
  content/articles/subscription-renewals.markdown
  content/articles/what-happens-if-i-stop-paying.markdown
  content/articles/yearly-billing.markdown
Labels: copy editing

#394 Account articles copy edits
  content/articles/account-invoice-history.markdown
  content/articles/billing-settings.markdown
  content/articles/close-account.markdown
  content/articles/reactivate-subscription.markdown
Labels: copy editing

#397 Account changes edits
  content/articles/account-creation.markdown
  content/articles/changing-account-email.markdown
  content/articles/changing-payment-details.markdown
  content/articles/changing-user-email.markdown
Labels: copy editing

#400 dns hosting copy edits
  content/articles/common-dns-records.markdown
  content/articles/dns-hosting.markdown
  content/articles/record-editor.markdown
  content/articles/supported-dns-records.markdown
Labels: copy editing, ready-for-review

#402 Update DNSSEC article
  content/articles/dnssec.markdown
Labels: enhancement
