Repository dnsimple/dnsimple-support, pull requests merged in 2018-11, with the labels that each got.

#368 Reasons hosting edits
  content/articles/reasons-hosting-dns.markdown
Labels: copy editing, ready-for-review

#367 Drop catch email hosting edit
  content/articles/drop-catching.markdown
Labels: copy editing, ready-for-review

#350 Add articles about adding specific record types
  content/articles/a-record.markdown
  content/articles/aaaa-record.markdown
  content/articles/auto-import-dns.markdown
  content/articles/caa-record.markdown
  content/articles/cname-record.markdown
  content/articles/dnssec.markdown
  content/articles/manage-a-record.markdown
  content/articles/manage-aaaa-record.markdown
  content/articles/manage-caa-record.markdown
  content/articles/manage-cname-record.markdown
  content/articles/manage-url-record.markdown
  content/articles/redirector.markdown
  content/articles/url-record.markdown
  content/files/record-a-create-new.png
  content/files/record-a-create-select.png
  content/files/record-a-item-delete.png
  content/files/record-a-item-edit.png
  content/files/record-a-item.png
  content/files/record-aaaa-create-new.png
  content/files/record-aaaa-create-select.png
  content/files/record-aaaa-item-delete.png
  content/files/record-aaaa-item-edit.png
  content/files/record-aaaa-item.png
  content/files/record-caa-create-new.png
  content/files/record-caa-create-select.png
  content/files/record-caa-item-delete.png
  content/files/record-caa-item-edit.png
  content/files/record-caa-item.png
  content/files/record-cname-create-new.png
  content/files/record-cname-create-select.png
  content/files/record-cname-item-delete.png
  content/files/record-cname-item-edit.png
  content/files/record-cname-item.png
  content/files/record-type-a.png
  content/files/record-url-create-new.png
  content/files/record-url-create-select.png
  content/files/record-url-item-delete.png
  content/files/record-url-item-edit.png
  content/files/record-url-item.png
  priorities/articles.yaml
Labels: articles, help wanted

#372 Update index.html
  content/index.html
Labels: copy editing, ready-for-review

#375 Update Common Name article
  content/articles/what-is-common-name.markdown
Labels: articles, ready-for-review

#379 Adds missing image
  content/files/domains-domain-link.png
Labels: bug, ready-for-review

#377 Duplicated search bar
  content/assets/css/_application.scss
  content/assets/css/_colors.scss
  content/assets/css/_typography.scss
  content/assets/css/_variables.scss
  content/assets/css/style.scss
  content/index.html
  layouts/input-search.html
Labels: articles, ready-for-review

#374 Separated enable and disable dns hosting
  content/articles/dns-hosting.markdown
  content/files/domain-dns-hosting-disable.png
  content/files/domain-tab-dns-link.png
Labels: articles, ready-for-review

#378 Account edits
  content/404.markdown
  content/articles/account-activation.markdown
  content/articles/account-creation.markdown
  content/articles/account-securing.markdown
  content/articles/account-suspended.markdown
Labels: copy editing, ready-for-review

#363 update_icann_verification
  content/articles/icann-domain-validation.markdown
Labels: enhancement, ready-for-review

#380 Update article about common records
  content/articles/common-dns-records.markdown
  content/articles/supported-dns-records.markdown
Labels: articles

#382 Updates the screenshots that show certificate names
  content/files/lets-encrypt-new-fixed.png
  content/files/lets-encrypt-new-names.png
  content/files/lets-encrypt-new-san.png
Labels: enhancement, ready-for-review

#383 App alert style in support alerts
  content/assets/css/_application.scss
  content/assets/css/_template.scss
  content/assets/css/_variables.scss
Labels: enhancement, ready-for-review

#385 Update screenshot with old logo
  content/files/secondary-dns-configured.jpg
Labels: articles, ready-for-review

#384 Cleanup the content of the SAN article
  content/articles/what-is-ssl-san.markdown
Labels: articles, ready-for-review

#387 Deleting avatar references on support site
  content/articles/account-multi.markdown
  content/articles/adding-domain.markdown
  content/articles/adding-subdomain.markdown
  content/articles/changing-domain-contact.markdown
  content/articles/delegating-dnsimple-registered.markdown
  content/articles/deleting-domain.markdown
  content/articles/domain-auto-renewal.markdown
  content/articles/installing-ssl-certificate.markdown
  content/articles/ordering-lets-encrypt-certificate.markdown
  content/articles/ordering-standard-certificate.markdown
  content/articles/registering-domain.markdown
  content/articles/reissuing-ssl-certificate.markdown
  content/articles/renewing-domain.markdown
  content/articles/renewing-lets-encrypt-ssl-certificate.markdown
  content/articles/renewing-standard-ssl-certificate.markdown
  content/articles/setting-name-servers.markdown
  content/articles/ssl-certificates-email-validation.markdown
  content/articles/ssl-certificates.markdown
  content/articles/transferring-domain-away.markdown
  content/articles/whois-privacy.markdown
  content/articles/zone-files.markdown
Labels: articles, bug, ready-for-review

#393 Add warning about setting name servers before transferring
  content/articles/transferring-domain-away.markdown
Labels: ready-for-review
