Repository dnsimple/dnsimple-support, pull requests merged in 2019-09, with the labels that each got.

#455 Remove IPS tags table
  content/articles/transferring-uk-domain.markdown
Labels: enhancement

#459 Add article about dig
  content/articles/how-dig.markdown
Labels: articles, ready-for-review

#460 Expand transfer out with instructions for starting the transfer
  content/articles/transferring-domain-away.markdown
Labels: articles

#464 Add reseller plans to https redirector requisites
  content/articles/redirector.markdown
Labels: enhancement, ready-for-review

#463 Remove basic reseller plan mention
  content/articles/new-plans.markdown
Labels: ready-for-review
