Repository dnsimple/dnsimple-support, pull requests merged in 2019-11, with the labels that each got.

#468 Update to Ruby v2.6.5
  .ruby-version
Labels: ready-for-review, task

#469 Add Q/A about Certificates validness after account unsubscribal
  content/articles/faq-ssl-certificates.markdown
Labels: enhancement, ready-for-review

#471 Remove CTA to contact support for uk transfer
  content/articles/domains-uk.markdown
Labels: articles, enhancement, invalid, ready-for-review

#472 Creates FAQ structure for Google search results
  Rules
  content/articles/faq-ssl-certificates.markdown
  lib/structured_data.rb
Labels: ready-for-review
