Repository dnsimple/dnsimple-support, pull requests merged in 2019-03, with the labels that each got.

#427 Redirect copy edits
  content/articles/redirect-heroku.markdown
  content/articles/redirect.markdown
  content/articles/redirector.markdown
  content/articles/troubleshooting-redirects.markdown
Labels: copy editing, ready-for-review

#428 Expiration copy edits
  content/articles/disabling-expiration-notifications.markdown
  content/articles/recovering-deleted-domain.markdown
  content/articles/what-happens-when-domain-expires.markdown
Labels: copy editing, ready-for-review

#430 Clarify information about email address used for notifications
  content/articles/product-expiration-notification.markdown
  content/articles/product-expiring-tomorrow-notification.markdown
Labels: articles, copy editing, ready-for-review

#432 Remove 2FA enforcement beta notice
  content/articles/two-factor-authentication-enforcement.markdown
Labels: enhancement, ready-for-review
