Repository dnsimple/dnsimple-support, pull requests merged in 2019-01, with the labels that each got.

#406 Troubleshooting copy edits
  content/articles/domain-resolution-issues.markdown
  content/articles/record-resolution-issues.markdown
Labels: copy editing, ready-for-review

#405 Why not hosting edits
  content/articles/why-not-web-hosting.markdown
Labels: copy editing, ready-for-review

#403 More record edits
  content/articles/mx-record.markdown
  content/articles/ns-record.markdown
  content/articles/pool-record.markdown
  content/articles/soa-record.markdown
  content/articles/spf-record.markdown
  content/articles/srv-record.markdown
  content/articles/url-record.markdown
Labels: copy editing, ready-for-review

#399 Last account article copy edits
  content/articles/account-multi.markdown
  content/articles/account-users.markdown
  content/articles/activity-tracking.markdown
  content/articles/setting-up-accounts-for-clients.markdown
  content/articles/two-factor-authentication.markdown
Labels: copy editing, ready-for-review

#388 Let's Encrypt Wildcard Certificates
  content/articles/caa-record.markdown
  content/articles/dnsimple-services.markdown
  content/articles/letsencrypt.markdown
  content/articles/ssl-certificate-authorities.markdown
  content/articles/ssl-certificates.markdown
  content/articles/standard-vs-letsencrypt.markdown
Labels: articles, ready-for-review

#390 Ordering wildcard certificate
  content/articles/ordering-standard-certificate.markdown
  content/articles/ordering-wildcard-certificate.markdown
  content/files/lets-encrypt-wildcard-order.png
  priorities/articles.yaml
Labels: articles, ready-for-review

#407 Screenshot updates for dashboard and record editor
  content/articles/reactivate-subscription.markdown
  content/files/account-dashboard-reactivation.jpg
  content/files/account-dashboard-reactivation.png
  content/files/rec-editor-access.png
  content/files/rec-editor-domain-page.png
  content/files/rec-editor-new-record.png
  content/files/rec-editor-page.png
Labels: ready-for-review

#409 Updates SSL Certificate Screenshots
  content/articles/installing-ssl-certificate.markdown
  content/articles/reissuing-ssl-certificate.markdown
  content/articles/ssl-certificates-email-validation.markdown
  content/files/certificate-letsencrypt-auto-renewal.png
  content/files/certificates-renew-action.png
  content/files/dnsimple-domain-certificatelist-issued.png
  content/files/dnsimple-domain-certificates-list.png
  content/files/dnsimple-ssl-completesetup.png
  content/files/dnsimple-ssl-pagelink-purchased.png
  content/files/dnsimple-ssl-reissue-link.png
  content/files/dnsimple-ssl-reissue-new.png
  content/files/dnsimple-ssl-resend-approval-link.png
  content/files/dnsimple-ssl-selectapprover.png
  content/files/domain-view-ssl-certificate-link.png
  content/files/ssl-authority-certificate.png
  content/files/ssl-authority-order.png
  content/files/ssl-certificate-install-link.png
  content/files/ssl-certificate-page.png
  content/files/ssl-certificate-reissue-confirm.png
  content/files/ssl-certificate-reissue-install.png
  content/files/ssl-certificate-reissue-link.png
Labels: enhancement, ready-for-review

#411 Updates screenshots for domain articles
  content/articles/adding-subdomain.markdown
  content/articles/changing-domain-contact.markdown
  content/articles/deleting-domain.markdown
  content/articles/google-apps-service.markdown
  content/articles/renewing-domain.markdown
  content/articles/secondary-dns.markdown
  content/articles/services.markdown
  content/articles/vanity-nameservers.markdown
  content/articles/whois-privacy.markdown
  content/files/activity-tracking-1.png
  content/files/change-contacts.jpg
  content/files/change-contacts.png
  content/files/delete-domain.jpg
  content/files/delete-domain.png
  content/files/disable-auto-renewal.png
  content/files/disable-expiration-notifications.png
  content/files/dnsimple-domain-tab-change-nameserver-link.png
  content/files/dnsimple-domain-tab-switch-nameserver-link.png
  content/files/dnssec-configuration-dsrecord.png
  content/files/dnssec-configure.png
  content/files/dnssec-configured.png
  content/files/dnssec-disable.png
  content/files/dnssec-enable.png
  content/files/dnssec-tab.png
  content/files/domain-dns-hosting-disable.png
  content/files/domain-dns-hosting-enable.png
  content/files/domain-transfer-out-action.png
  content/files/domain.jpg
  content/files/email-forwarding-removal.png
  content/files/email-forwarding.png
  content/files/enable-auto-renewal.png
  content/files/example-domain-manage.png
  content/files/renew-domain.jpg
  content/files/renew-domain.png
  content/files/resolution-status-expired.png
  content/files/resolution-status-notresolving-maintained.png
  content/files/resolution-status-notresolving-notmaintained.png
  content/files/resolution-status-resolving.png
  content/files/secondary-dns-configured.jpg
  content/files/secondary-dns-configured.png
  content/files/secondary-dns-confirmation-message.png
  content/files/secondary-dnsimple-1.png
  content/files/services-after-added.jpg
  content/files/services-card.png
  content/files/services-dns-page-add.png
  content/files/services-dns-page-manage.png
  content/files/services-dns-page.png
  content/files/settings-tab.png
  content/files/setup-secondary-dns.png
  content/files/share-management-card.png
  content/files/transfer-ownership.png
  content/files/vanity-name-servers-card-disable.png
  content/files/vanity-name-servers-card-enable.png
  content/files/vanity-name-servers-card.png
  content/files/whoisprivacy-domain-card-disabled.png
  content/files/whoisprivacy-domain-card-enabled.png
  content/files/whoisprivacy-domain-card-renew.png
  content/files/whoisprivacy-enable-page.png
Labels: ready-for-review

#413 dns support copy edits
  content/articles/dns-query-limits.markdown
  content/articles/dnssec.markdown
  content/articles/dynamic-dns.markdown
  content/articles/resolution-status.markdown
  content/articles/what-minimum-time-to-live.markdown
Labels: copy editing, ready-for-review

#412 Records copy edits
  content/articles/auto-import-dns.markdown
  content/articles/ds-records-changing-dns.markdown
  content/articles/redirector-https.markdown
  content/articles/regional-records.markdown
Labels: copy editing, ready-for-review

#408 Anycast & differences copy edits
  content/articles/anycast.markdown
  content/articles/differences-a-cname-records.markdown
  content/articles/differences-between-a-cname-alias-url.markdown
  content/articles/why-anycast-dns.markdown
Labels: copy editing, ready-for-review

#410 Record & zone copy edits
  content/articles/dkim-record.markdown
  content/articles/how-long-does-it-take-for-a-new-record-to-resolve-for-my-domain.markdown
  content/articles/reverse-dns.markdown
  content/articles/zone-files.markdown
Labels: copy editing, ready-for-review

#414 Secondary dns copy edits
  content/articles/secondary-dns-provider-dns-made-easy.markdown
  content/articles/secondary-dns-provider-dyn.markdown
  content/articles/secondary-dns-provider-easy-dns.markdown
  content/articles/secondary-dns.markdown
  content/articles/secondary-dnsimple.markdown
Labels: copy editing, ready-for-review

#416 Add section about CDS/CDNSKEY to DNSSEC article
  content/articles/dnssec.markdown
Labels: enhancement, ready-for-review
