Repository dnsimple/dnsimple-support, pull requests merged in 2019-05, with the labels that each got.

#435 Update the .UK error list
  content/articles/domains-uk.markdown
Labels: articles, ready-for-review

#434 Update Record Index to Include DKIM and Fix Link to TXT Record by creating TXT Record page
  content/articles/common-dns-records.markdown
  content/articles/txt-record.markdown
Labels: articles

#436 Refresh screenshot when confirming certificate request
  content/files/ssl-certificate-reissue-confirm.png
Labels: enhancement

#437 Upgrades to Global Site Tag (gtag.js)
  layouts/analytics.html
Labels: enhancement

#438 Clarify supported SSL certificate validations via acronyms
  content/articles/letsencrypt.markdown
Labels: enhancement, ready-for-review
