Repository dnsimple/dnsimple-support, pull requests merged in 2020-10, with the labels that each got.

#658 Document special .be procedures
  content/articles/domains-be.markdown
Labels: articles

#661 Bumps serialize-javascript
  yarn.lock
Labels: dependencies, task

#663 Updates dictionary to match annual to yearly
  templates/dictionary.json.erb
Labels: enhancement, ready-for-review
