Repository dnsimple/dnsimple-support, pull requests merged in 2020-12, with the labels that each got.

#690 Lets encrypt article edits
  content/articles/letsencrypt.markdown
Labels: copy editing

#696 Billing information (not email) can be customized on any plan
  content/articles/billing-settings.markdown
Labels: articles, copy editing, enhancement, ready-for-review

#703 Upgrade to Ruby v2.7.2 and NodeJS v14.15.3 LTS
  .tool-versions
  .travis.yml
Labels: dependencies, enhancement, ready-for-review
