Repository dnsimple/dnsimple-support, pull requests merged in 2020-03, with the labels that each got.

#520 Merge transferring .UK domains pages
  content/articles/domains-uk.markdown
  content/articles/transferring-uk-domain.markdown
Labels: enhancement, ready-for-review

#524 Add `+trace` blurb for Record Resolution Issues article
  content/articles/record-resolution-issues.markdown
Labels: enhancement, ready-for-review

#525 Restores Travis config without the deployment step
  .tool-versions
  .travis.yml
Labels: enhancement, ready-for-review

#530 Fixes check for invalid content
  _test/content_test.rb
  content/articles/activity-tracking.markdown
  content/articles/cloudflare-ds-record.markdown
  content/articles/domains-es.markdown
  content/articles/reasons-registering-domain.markdown
  content/articles/secondary-dns-provider-dns-made-easy.markdown
  content/articles/why-anycast-dns.markdown
  content/articles/why-not-web-hosting.markdown
Labels: bug, ready-for-review

#517 Create writing-guide.markdown
  content/articles/writing-guide.markdown
Labels: articles, ready-for-review

#531 Updates articles for new delegation logic
  content/articles/delegating-dnsimple-registered.markdown
  content/articles/setting-name-servers.markdown
  content/files/domain-delegation-card.png
Labels: enhancement, ready-for-review

#537 Adds verification requirement information to changing contact details
  content/articles/changing-whois-contact.markdown
Labels: articles, ready-for-review
