Repository dnsimple/dnsimple-support, pull requests merged in 2020-09, with the labels that each got.

#644 Fixes duplicate warning about secondary DNS
  content/articles/secondary-dns.markdown
Labels: articles, bug

#645 Updates image for dnssec article
  content/files/dnssec-enable.png
Labels: articles, bug

#646 Updates with a warning that wildcard certificates do not cover root
  content/articles/ordering-wildcard-certificate.markdown
Labels: articles, enhancement

#648 Add `search.js`
  .eslintignore
  .eslintrc.js
  .travis.yml
  _headers
  content/articles/edns-client-subnet.markdown
  content/assets/js/search.js
  content/assets/js/vendor/lunr.min.js
  content/search.html
  content/search/results.js
  jest.config.js
  layouts/default.html
  lib/search.rb
  package.json
  spec/search/index.spec.js
  spec/search/results.spec.js
  src/index.js
  templates/dictionary.json.erb
  templates/search.js.erb
  yarn.lock
Labels: enhancement, javascript, ready-for-review

#652 Put title for DNSSEC/Secondary in correct place
  content/articles/dnssec-and-secondary-dns.markdown
Labels: bug

#656 Bumps serialize-javascript version
  yarn.lock
Labels: dependencies

#651 EDNS cdn update
  content/articles/edns-client-subnet.markdown
Labels: articles, copy editing
