Repository dnsimple/dnsimple-support, pull requests merged in 2020-08, with the labels that each got.

#594 Updates to SSL-related content
  content/articles/what-is-ssl-certificate-chain.markdown
  content/articles/what-is-ssl-root-certificate.markdown
  content/files/dnsimple-ssl-chain.png
Labels: articles, copy editing, enhancement, ready-for-review

#617 Add default styling to tables
  content/articles/a-record.markdown
  content/articles/aaaa-record.markdown
  content/articles/caa-record.markdown
  content/articles/cname-record.markdown
  content/articles/url-record.markdown
  content/assets/css/_tables.scss
  content/assets/css/_typography.scss
  content/assets/css/style.scss
Labels: bug

#616 Add subheadings to "Difference Between A and CNAME Records"
  content/articles/differences-a-cname-records.markdown
Labels: copy editing, enhancement

#589 Redirector and push edits
  content/articles/adding-domain.markdown
  content/articles/deleting-domain.markdown
  content/articles/domain-auto-renewal.markdown
  content/articles/recovering-deleted-domain.markdown
  content/articles/redirector.markdown
  content/articles/registering-domain.markdown
  content/articles/transferring-domain-away.markdown
  content/articles/transferring-domain-between-accounts.markdown
  content/files/add-a-domain.png
  content/files/registering-a-new-domain.png
  content/files/transferring-a-domain.png
  content/files/zone-import-tool.png
Labels: articles, enhancement, ready-for-review

#618 Update docs to reflect 1-year certificate lifetime transition
  content/articles/can-multi-year-ssl-certificates.markdown
  content/articles/letsencrypt.markdown
Labels: articles

#622 Add clarity to UK registrant name changes
  content/articles/domains-uk.markdown
  content/files/uk-ownership.png
Labels: enhancement, ready-for-review

#626 Add links to headlines
  layouts/default.html
Labels: enhancement, ready-for-review

#621 Registration agreement support pages
  content/articles/tlds-registry-agreements.markdown
  content/articles/tlds-regulated.markdown
Labels: articles, ready-for-review

#633 Updates serialize-javascript dependency
  yarn.lock
Labels: dependencies, enhancement

#634 Add note about how issuewild takes precedence over issue
  content/articles/caa-record.markdown
Labels: articles, enhancement, ready-for-review

#640 Updates serialize-javascript dependency
  yarn.lock
Labels: dependencies, task
