Repository dnsimple/dnsimple-support, pull requests merged in 2020-02, with the labels that each got.

#505 Adds instructions on how to cancel a transfer
  content/articles/transferring-domain.markdown
Labels: enhancement, ready-for-review

#512 Update TLD support articles
  content/articles/domains-ch.markdown
  content/articles/domains-es.markdown
  content/articles/domains-io.markdown
  content/articles/domains-it.markdown
Labels: articles

#513 Update auto-renewal domain information
  content/articles/auto-renew-only-domains.markdown
  content/articles/domains-ch.markdown
  content/articles/domains-es.markdown
  content/articles/domains-li.markdown
Labels: articles

#426 Domain management edits
  content/articles/labeling-domains.markdown
  content/articles/sharing-domain.markdown
  content/articles/transferring-domain-between-accounts.markdown
  content/articles/web-hosting.markdown
Labels: copy editing, ready-for-review

#515 Updates site to use asdf
  .ruby-gemset
  .ruby-version
  .tool-versions
  README.md
Labels: enhancement, ready-for-review

#516 Cloudflare and DNSSEC article fix
  content/articles/cloudflare-ds-record.markdown
  content/files/dnssec-ds-record-1.png
  content/files/dnssec-ds-record-2.png
Labels: enhancement, ready-for-review
