Repository dnsimple/dnsimple-support, pull requests merged in 2022-08, with the labels that each got.

#931 Improves custom CAA value field documentation
  content/articles/caa-record.markdown
Labels: ready-for-review

#935 Adds IPv6 entries when configuring AXFR for DNSimple as Secondary
  content/articles/secondary-dns-dnsimple-as-secondary.markdown
Labels: enhancement, ready-for-review

#934 Document delegation improvements
  content/articles/dnssec.markdown
  content/articles/secondary-dns.markdown
  content/files/delete-secondary-dns.png
  content/files/dnssec-disable-hosted.png
  content/files/dnssec-enable-warning.png
  content/files/reconfigure-secondary-dns.png
  content/files/secondary-dns-configured.png
  content/files/secondary-dns-warning.png
Labels: enhancement
