Repository dnsimple/dnsimple-support, pull requests merged in 2022-09, with the labels that each got.

#933 Adjust the name of the commercial SSL certificate products we sell
  content/articles/ssl-certificates.markdown
Labels: enhancement

#938 Document Cloudflare one-click service deprecation
  content/articles/cloudflare-service.markdown
Labels: articles

#940 Small TXT record doc improvements
  content/articles/txt-record.markdown
Labels: ready-for-review

#941 Remove section about existing name with DNSimple
  content/articles/domains-au.markdown
Labels: articles

#942 Remove AUda direct info
  content/articles/domains-au.markdown
Labels: articles

#944 Sub categories for categories pages
  README.md
  _test/subcategories_test.rb
  categories/account.yaml
  categories/api.yaml
  categories/connectors.yaml
  categories/contacts.yaml
  categories/dns.yaml
  categories/dnsimple.yaml
  categories/dnssec.yaml
  categories/domain_transfers.yaml
  categories/domains.yaml
  categories/emails.yaml
  categories/integrations.yaml
  categories/name_servers.yaml
  categories/secondary_dns.yaml
  categories/services.yaml
  categories/ssl_certificates.yaml
  categories/templates.yaml
  categories/whois_privacy.yaml
  content/articles/cloudflare-ds-record.markdown
  content/articles/cloudflare-service.markdown
  content/articles/consul-integration.markdown
  content/articles/domain-apex-heroku.markdown
  content/articles/heroku-connector.markdown
  content/articles/heroku-error-differentapp.markdown
  content/articles/heroku-error-nosuchapp.markdown
  content/articles/heroku-error-ssl.markdown
  content/articles/redirect-heroku.markdown
  content/articles/ssl-certificate-with-heroku.markdown
  content/articles/terraform-provider.markdown
  layouts/category_index.html
  lib/default.rb
  lib/sub_categories.rb
  priorities/articles.yaml
Labels: enhancement

#945 Bumps node version
  .node-version
  .tool-versions
Labels: dependencies
