Repository dnsimple/dnsimple-support, pull requests merged in 2022-07, with the labels that each got.

#916 Adds IPv6 for axfr.dnsimple.com
  content/articles/secondary-dns-provider-dns-made-easy.markdown
  content/articles/secondary-dns-provider-easy-dns.markdown
  content/articles/secondary-dns.markdown
Labels: enhancement, ready-for-review

#924 Improve Let's Encrypt docs
  Gemfile.lock
  content/articles/ordering-lets-encrypt-certificate.markdown
Labels: enhancement, ready-for-review

#929 Bumps ruby version to 3.1.2
  .ruby-version
  .tool-versions
Labels: dependencies

#928 Adds UTM tracking for CTAs and links to dnsimple-app
  layouts/default.html
Labels: enhancement
