Repository dnsimple/dnsimple-support, pull requests merged in 2022-10, with the labels that each got.

#947 Adds announcement and social proof section
  content/assets/images/features/two-step-verification.png
  content/assets/images/vendors/linux-foundation-vert-color.svg
  content/index.html
Labels: enhancement

#949 Add instructions for .DAY
  content/articles/domains-day.markdown
Labels: articles

#948 Update support article on our level of support of ECC signed SSL certificates
  content/articles/can-elliptic-curve-key-ssl-certificates.markdown
Labels: enhancement

#950 Domain list UI updates
  content/files/enter-labels.png
  content/files/filtering-by-labels.png
  content/files/labels-and-domains.png
  content/files/pending-push-notification.png
  content/files/pending-pushes.jpg
  content/files/rec-editor-access.png
  content/files/rec-editor-delete.png
  content/files/rec-editor-edit.png
  content/files/rec-editor-page.png
  content/files/selecting-domains.png
Labels: articles

#953 Dark theme
  content/assets/css/_application.scss
  content/assets/css/_tables.scss
  content/assets/css/_template.scss
  content/assets/css/_typography.scss
  content/assets/css/_variables.scss
  content/assets/css/colorscheme.scss
  content/assets/css/style.scss
  content/assets/images/dnsimple-logo-support.svg
  content/assets/images/moon.svg
  content/assets/images/sun.svg
  content/assets/images/vendors/linux-foundation-color.png
  content/assets/images/vendors/linux-foundation-vert-color.svg
  content/assets/images/vendors/linux-foundation-white.png
  content/index.html
  layouts/colortheme.html
  layouts/default.html
  src/index.js
Labels: enhancement

#952 Introduce API Errors article
  categories/api.yaml
  content/articles/api-errors.markdown
Labels: articles

#951 Document Record Notes
  categories/dns.yaml
  content/articles/manage-a-record.markdown
  content/articles/manage-aaaa-record.markdown
  content/articles/manage-caa-record.markdown
  content/articles/manage-cname-record.markdown
  content/articles/manage-url-record.markdown
  content/articles/record-notes.markdown
  content/files/record-a-create-new.png
  content/files/record-aaaa-create-new.png
  content/files/record-caa-create-new.png
  content/files/record-cname-create-new.png
  content/files/record-notes-activities.png
  content/files/record-notes-delete.png
  content/files/record-notes-deletion-note.png
  content/files/record-notes-edit.png
  content/files/record-notes.png
  content/files/record-url-create-new.png
Labels: articles

#957 Adds Google Analytics 4
  layouts/analytics.html
  nanoc.yaml
Labels: enhancement

#958 Adds ns4.dnsimple-edge.org NS to the list
  content/articles/delegating-dnsimple-hosted.markdown
  content/articles/dnsimple-nameservers.markdown
  content/articles/manage-caa-record.markdown
  content/articles/ns-record.markdown
  content/articles/supported-dns-records.markdown
Labels: ready-for-review

#961 Remove false identity provider promise when resetting a password
  content/articles/forgot-password.markdown
Labels: bug
