Repository dnsimple/dnsimple-support, pull requests merged in 2023-09, with the labels that each got.

#1088 Add GoDaddy walkthrough video
  content/articles/integrated-domain-provider-godaddy.markdown
Labels: enhancement

#1085 Refresh article about DNS query limits and fees
  categories/dns.yaml
  categories/dnsimple.yaml
  content/articles/dns-query-limits.markdown
Labels: articles

#1086 Add a link to query volume entries in understanding your invoice
  content/articles/understanding-invoice.markdown
  content/files/recurring-charges.png
Labels: articles

#1087 Explain the pay as you go model for hosted zones and DNS query volume.
  content/articles/dnsimple-plans.markdown
Labels: articles

#1084 Reflect new plan names in plan-changes page
  content/articles/changing-plans.markdown
  content/files/account-billing-cancel-plan-change.png
  content/files/account-billing-change-plan-link.png
  content/files/account-billing-incompatible-features.png
  content/files/change-plan-2.png
  content/files/change-plan-3.png
Labels: documentation

#1090 fix: Change the incompatible feature message for seat to make sense
  content/files/account-billing-incompatible-features.png
Labels: copy editing

#1080 Managing seats article
  categories/account.yaml
  content/articles/account-users.markdown
  content/articles/managing-seats.markdown
  content/files/adding-seats-when-inviting-new-members.png
  content/files/decreasing-seats.png
Labels: documentation
