Repository dnsimple/dnsimple-support, pull requests merged in 2023-07, with the labels that each got.

#1063 Refresh feature announcements
  content/assets/images/features/whats-new-april-2023.png
  content/assets/images/features/whats-new-summer-2023.png
  content/index.html
Labels: task

#1060 New article about account information
  categories/account.yaml
  content/articles/changing-account-information.markdown
  content/files/account-edit.png
  content/files/account-information-form.png
Labels: articles

#1062 Add stateful trades contact change docs
  content/articles/changing-domain-contact.markdown
  content/articles/contact-management.markdown
  content/files/change-contact-1.jpg
  content/files/change-contact-1.png
  content/files/change-contact-confirmation.png
  content/files/change-contact-preview.png
  content/files/change-contacts.png
  content/files/contact-change-confirmation.png
  content/files/contact-change-monitor.png
  content/files/domain-contact-change-lock.png
  content/files/domain-registration-details.png
  content/files/domains-domain-link.png
  content/files/edit-existing-contact-1.jpg
  content/files/edit-existing-contact-1.png
Labels: enhancement

#1067 Change image for pending contact change
  content/files/contact-change-monitor.png
Labels: articles

#1070 Update setting-name-servers.markdown
  content/articles/delegating-dnsimple-registered.markdown
  content/articles/setting-name-servers.markdown
Labels: articles
