Repository dnsimple/dnsimple-support, pull requests merged in 2023-03, with the labels that each got.

#1007 Delete TLD Agreements list
  categories/domains.yaml
  content/articles/tlds-registry-agreements.markdown
Labels: task

#1006 Article: Leave a review
  content/articles/leave-a-review.markdown
Labels: articles

#1005 Okta: Update configuration instructions for Okta SSO
  content/articles/okta-identity-provider.markdown
  content/files/okta-assignment.png
  content/files/okta-client-details.png
  content/files/okta-create-app-integration-form.png
  content/files/okta-create-app-integration.png
  content/files/okta-grant-scopes.png
  content/files/okta-link-account.png
  content/files/okta-reauthorize.png
Labels: articles

#1011 Add Okta SSO video walk-through
  content/articles/okta-identity-provider.markdown
Labels: enhancement

#1013 Adds Okta as a new feature
  content/assets/images/features/name-server-sets.jpg
  content/assets/images/features/okta.png
  content/index.html
Labels: enhancement

#1015 Correction for the "Managing Multiple Members on One Account" article
  content/articles/account-users.markdown
Labels: enhancement
