Repository dnsimple/dnsimple-support, pull requests merged in 2023-04, with the labels that each got.

#1020 Removes hotjar
  layouts/default.html
  layouts/hotjar.html
Labels: task

#1021 Fixes text too small to read
  content/articles/how-to-different-ssl-domain-validation-email.markdown
  content/assets/css/_typography.scss
Labels: task

#1022 Lazy load images
  lib/postprocess_filter.rb
Labels: enhancement

#1019 Updates WhoisPrivacy enable/disable docs
  content/articles/whois-privacy.markdown
  content/files/whoisprivacy-disable-page.png
  content/files/whoisprivacy-domain-card-disabled.png
  content/files/whoisprivacy-domain-card-enabled.png
  content/files/whoisprivacy-domain-card-renew.png
  content/files/whoisprivacy-enable-page.png
Labels: bug

#1023 Compress images over 200KB
  content/files/activity-tracking-2.png
  content/files/activity-tracking-5.png
  content/files/au-priority-registration-process.png
  content/files/certificate-installer-apache.png
  content/files/certificate-installer-azure.png
  content/files/certificate-installer-heroku.png
  content/files/certificate-installer-iis.png
  content/files/certificate-installer-nginx.png
  content/files/certificate-installer-other.png
  content/files/change-plan-2.png
  content/files/contact-change.png
  content/files/dnsimple-certificate-purchase.png
  content/files/dnsimple-certificate-renewal.png
  content/files/dnsimple-ssl-chain.png
  content/files/dnsimple-ssl-completesetup.png
  content/files/dnsimple-ssl-pagelink-submitted.png
  content/files/dnsimple-ssl-reissue-new.png
  content/files/dnsimple-ssl-resend-approval-link.png
  content/files/domain-access-control-domain-manager.png
  content/files/domain-access-control-zone-operator.png
  content/files/domain-expiration-email-2.png
  content/files/domain-push-email.png
  content/files/ds-records-add-ds-record.png
  content/files/ds-records-list.png
  content/files/ds-records-manage.png
  content/files/easy-dns-add-domain.png
  content/files/easy-dns-confirm.png
  content/files/easy-dns-domain-admin.png
  content/files/easy-dns-secondary-zone.png
  content/files/easy-dns-tools.png
  content/files/google-sso-enable.png
  content/files/nominet-uk-1.png
  content/files/nominet-uk-2.png
  content/files/nominet-uk-3.png
  content/files/oauth-location.png
  content/files/prorated-invoice.png
  content/files/reconfigure-secondary-dns.png
  content/files/record-a-create-select.png
  content/files/record-aaaa-create-select.png
  content/files/record-caa-create-select.png
  content/files/record-cname-create-select.png
  content/files/record-url-create-select.png
  content/files/recurring-charges.png
  content/files/register-eu-domain.png
  content/files/secondary-dns-tab.png
  content/files/services-amazon-elasticbeanstalk.png
  content/files/services-amazon-lightsail.png
  content/files/services-atmail.png
  content/files/services-google-apps.png
  content/files/services-jimdo.png
  content/files/services-postmark-dmarc.png
  content/files/services-postmark.png
  content/files/services-windows-azure.png
  content/files/ssl-certificate-installation-page.png
  content/files/ssl-certificate-reissue-confirm.png
  content/files/ssl-certificate-reissue-link.png
  content/files/uk-domain-transfer-out-ips-tag.png
Labels: task

#1025 Fix 404 links
  _test/links_test.rb
  content/articles/account-users.markdown
  content/articles/changing-whois-contact.markdown
  content/articles/email-forwarding.markdown
  content/articles/i-got-an-ecc-certificate-but-i-want-a-rsa-one.markdown
  content/articles/ns-record.markdown
  content/articles/ordering-wildcard-certificate.markdown
  content/articles/payment-methods.markdown
  content/articles/subscription-renewals.markdown
Labels: bug

#1026 Adds automated tests
  _test/content_test.rb
  _test/filename_test.rb
  _test/imagesize_test.rb
  _test/links_test.rb
  _test/subcategories_test.rb
Labels: enhancement

#1027 Update account unsubscribe information to consider whois privacy disable
  content/articles/cancel-subscription.markdown
  content/articles/what-happens-if-i-stop-paying.markdown
  content/files/account-unsubscribe-confirmation.png
  content/files/account-unsubscribe.png
Labels: enhancement

#1029 Remove Whois Privacy as purchasable product from the docs
  content/articles/account-subscription-balance.markdown
  content/articles/expiring-product-email-notifications.markdown
  content/articles/payment-methods.markdown
  content/articles/renewing-domain.markdown
  content/articles/understanding-invoice.markdown
  content/files/notifications-expiring-tomorrow.png
  content/files/notifications-expiring.png
  content/files/renew-domain-form.png
Labels: enhancement

#1030 Remove whois privacy renewal section
  content/articles/whois-privacy.markdown
  content/files/whoisprivacy-domain-card-enabled.png
  content/files/whoisprivacy-purchase-page.png
Labels: enhancement, articles
