Repository dnsimple/dnsimple-support, pull requests merged in 2024-03, with the labels that each got.

#1153 Updating the DCP graphic to include Azure
  content/assets/images/features/dcp.png
Labels: task

#1148 Document Azure Integration
  categories/integrations.yaml
  content/articles/integrated-dns-provider-amazon-route53.md
  content/articles/integrated-dns-provider-azure-dns.md
  content/articles/integrated-dns-provider-coredns.md
  content/articles/integrated-dns-providers.md
  content/files/account-integrated-provider-link.png
  content/files/account-integrated-provider-unlink.png
  content/files/account-integrated-providers.png
  content/files/dns-zone-providers-add-to-linked-provider.png
  content/files/dns-zone-providers-add-to-unlinked-provider.png
  content/files/dns-zone-providers-add-zone.png
  content/files/dns-zone-providers-delete-zone.png
  content/files/dns-zone-providers-delete.png
  content/files/integrated-dns-provider-azure.png
Labels: documentation

#1155 Let's Encrypt GA
  content/articles/letsencrypt.md
  content/articles/ordering-lets-encrypt-certificate.md
Labels: documentation

#1158 Update DNS Zone Providers images and text
  content/articles/integrated-dns-providers.md
  content/files/dns-zone-providers-add-to-linked-provider.png
  content/files/dns-zone-providers-add-to-unlinked-provider.png
  content/files/dns-zone-providers-add-zone.png
  content/files/dns-zone-providers-delete-zone.png
  content/files/dns-zone-providers-delete.png
Labels: documentation

#1162 Updating missing meta tags
  content/articles/resolving-with-us.html
  content/search.html
Labels: copy editing
