Repository dnsimple/dnsimple-support, pull requests merged in 2024-08, with the labels that each got.

#1226 Add CA registration requirements
  categories/domains.yaml
  content/articles/domains-ca.md
Labels: articles

#1225 Update DNSSEC & SecondaryDNS RFC
  content/articles/dnssec-and-secondary-dns.md
  content/articles/dnssec.md
  content/articles/secondary-dns-dnsimple-as-secondary.md
  content/articles/secondary-dns.md
Labels: documentation, copy editing

#1237 Create announcement-discontinue-vanity-for-grandfathered-domains
  content/articles/announcement-vanity-basic-reseller.md
  content/articles/announcement-vanity-grandfathered-domains.md
Labels: documentation
