Repository dnsimple/dnsimple-support, pull requests merged in 2024-05, with the labels that each got.

#1170 Indicate that ALIAS alternate TXT records are being deprecated
  content/articles/alias-record.md
Labels: documentation

#1172 Update outbound AXFR IPs
  content/articles/secondary-dns.md
Labels: task

#1182 Create announcement-vanity-basic-reseller
  content/articles/announcement-vanity-basic-reseller.md
Labels: documentation

#1180 Adds description for onboarding DNS records to a zone
  content/articles/dns-hosting.md
Labels: copy editing
