Repository dnsimple/dnsimple-support, pull requests merged in 2024-10, with the labels that each got.

#1262 Adding dual CTA to the support site
  content/assets/css/_dual_cta.scss
  content/assets/css/style.scss
  content/index.html
  layouts/default.html
Labels: site-generator

#1266 updating the H1 for better SEO
  content/index.html
Labels: copy editing

#1267 Add AU migration article
  content/articles/au-migration.md
Labels: articles

#1268 Add redirect to AU article
  _redirects
Labels: task

#1269 Updates screenshots for Secondary DNS generic article
  content/files/delete-secondary-dns.png
  content/files/reconfigure-secondary-dns.png
  content/files/secondary-dns-configured.png
  content/files/secondary-dns-custom.png
  content/files/secondary-dns-name-server-set.png
  content/files/secondary-dns-warning.png
Labels: documentation, task, articles

#1245 Update easydns axfr address & instructions
  categories/secondary_dns.yaml
  content/articles/secondary-dns-provider-easy-dns.md
  content/files/easy-dns-add-domain.png
  content/files/easy-dns-adding-dnsimple-ip.png
  content/files/easy-dns-confirm.png
  content/files/easy-dns-domain-admin.png
  content/files/easy-dns-get-dns.png
  content/files/easy-dns-ready-to-configure.png
  content/files/easy-dns-tools.png
Labels: documentation, task, articles

#1246 Update DNSMadeEasy axfr address and screenshots
  content/articles/secondary-dns-provider-dns-made-easy.md
  content/files/dns-made-easy-ip-set.png
  content/files/dns-made-easy-sync.png
  content/files/dns-made-easy-working.png
Labels: documentation, task, articles

#1251 Add axfr address to dyn support article
  categories/secondary_dns.yaml
  content/articles/secondary-dns-provider-dyn.md
Labels: documentation, task, articles

#1271 Add `tld` as a field in the domain name export file
  content/articles/export-domain-names-to-file.md
Labels: documentation

#1273 Add .BE/.BERLIN domain information
  README.md
  categories/domains.yaml
  content/articles/domains-be.md
  content/articles/domains-berlin.md
  content/files/domains-be.png
Labels: documentation, copy editing
