Repository dnsimple/dnsimple-support, pull requests merged in 2024-12, with the labels that each got.

#1312 Update the API access tokens article
  content/articles/api-access-token.md
  content/files/access-token-generated.png
  content/files/access-token-remove.png
  content/files/access-tokens-last-used.png
  content/files/scoped-account-token-permissions.png
  content/files/scoped-account-token-select-zones.png
  content/files/scoped-account-token-view.png
Labels: documentation

#1317 Adding social links in footer to be consistent across web properties
  content/assets/css/colorscheme.scss
  layouts/default.html
  layouts/social_links.html
Labels: site-generator

#1322 Add .SE domains page information
  categories/domains.yaml
  content/articles/domains-se.md
Labels: documentation

#1327 Add .JOBS support docs
  content/articles/domains-jobs.md
Labels: documentation

#1326 Update AU support docs
  content/articles/domains-au.md
Labels: documentation, copy editing

#1333 Updates Ruby runtime to 3.3.5
  .ruby-version
  .tool-versions
Labels: dependencies

#1334 Update Node runtime to 22.10.0
  .node-version
  .tool-versions
Labels: dependencies

#1341 Update GDPR domains page
  content/articles/domain-privacy-after-gdpr.md
  content/files/gdpr-disclosure.png
Labels: documentation

#1339 Add CNR suspended nameservers
  content/articles/icann-domain-validation.md
Labels: documentation

#1336 Add MX domains page
  categories/domains.yaml
  content/articles/domains-mx.md
Labels: documentation

#1335 Fix copy on auto-renewal required text
  content/articles/domains-ch.md
  content/articles/domains-es.md
  content/articles/domains-li.md
Labels: documentation, copy editing

#1340 Update SG domains page
  content/articles/domains-sg.md
Labels: documentation

#1338 Add JP domains page
  categories/domains.yaml
  content/articles/domains-jp.md
Labels: documentation
