Repository dnsimple/dnsimple-support, pull requests merged in 2024-11, with the labels that each got.

#1244 DNS Articles Critical Updates - 2
  content/articles/dns-hosting.md
  content/articles/record-editor.md
  content/articles/regional-records.md
  content/articles/resolution-status.md
  content/articles/transferring-domain-between-accounts.md
  content/files/choose-regions.png
  content/files/custom-vs-system-record.png
  content/files/delete-record.png
  content/files/dns-tab.png
  content/files/external-nameservers.png
  content/files/inactive-zone.png
  content/files/modify-record.png
  content/files/nameserver-list.png
  content/files/switch-to-simple-editor.png
  content/files/transfer-domain-card.png
  content/files/transfer-domains-between-accounts.png
Labels: documentation, help wanted

#1275 Final Critical Domain Article Edits
  categories/domains.yaml
  content/articles/adding-domain.md
  content/articles/adding-subdomain.md
  content/articles/domains-eu.md
  content/articles/icann-domain-validation.md
  content/articles/superlock.md
  content/files/dns-badge.png
  content/files/eu-declare-country.png
  content/files/naming-subdomain.png
  content/files/subdomain-choose-type.png
Labels: documentation, help wanted

#1277 Removes GA4
  layouts/analytics.html
  nanoc.yaml
Labels: task

#1274 making the header sticky
  content/assets/css/_application.scss
  layouts/default.html
Labels: site-generator

#1286 bump up the font size of dnsimple.com link in the footer
  layouts/default.html
Labels: site-generator

#1272 Remove mentions to the DNSimple Slack Integration
  categories/integrations.yaml
  content/articles/slack-integration.md
  content/files/slack-integration-step-2.png
  content/files/slack-integration-step-3.png
Labels: documentation

#1287 Updates on domain delegation
  content/articles/delegating-dnsimple-registered.md
  content/articles/setting-name-servers.md
  content/files/complete-name-server-change.png
  content/files/use-dnsimple-name-servers-confirmation.png
  content/files/use-dnsimple-name-servers.png
Labels: documentation

#1297 Document reserved name servers
  content/articles/setting-name-servers.md
  content/files/reserved-name-servers-edit-configuration.png
  content/files/reserved-name-servers.png
Labels: documentation

#1296 Fixing broken links
  content/articles/dkim-record.md
  content/articles/dmarc-record.md
  content/articles/domains-uk.md
  content/articles/format-service.md
  content/articles/integrated-dns-provider-coredns.md
  content/articles/kickofflabs-service.md
  content/articles/manage-ds-record.md
  content/articles/oauth-applications.md
  content/articles/pobox-service.md
  content/articles/wordpress.md
Labels: documentation

#1283 Critical Updates Contacts, Emails, Connectors
  categories/contacts.yaml
  content/articles/changing-domain-contact.md
  content/articles/contact-management.md
  content/articles/email-forwarding.md
  content/articles/heroku-connector.md
  content/articles/netlify-connector.md
  content/files/add-connector.png
  content/files/confirm-contact-change.png
  content/files/edit-contact.png
  content/files/forwarding-tab.png
  content/files/new-contacts.png
  content/files/new-email-forward.png
  content/files/registration-edit-contact.png
Labels: documentation, help wanted

#1253 Critical updates to articles in the DNS section - final articles
  content/articles/auto-import-dns.md
  content/articles/dnssec.md
  content/articles/okta-identity-provider.md
  content/articles/record-notes.md
  content/articles/zone-ns-records.md
  content/files/dns-badge.png
  content/files/dns-record-note.png
  content/files/dnssec-config.png
  content/files/dnssec-disable.png
  content/files/dnssec-enable.png
  content/files/edit-dnssec.png
  content/files/zone-records-edit.png
Labels: documentation, help wanted

#1276 updating some meta descriptions
  content/articles/account-activation.md
  content/articles/edns-client-subnet.md
  content/articles/how-dig.md
  content/articles/how-to-determine-certificate-authority.md
  content/articles/payment-methods.md
  content/articles/resolving-with-us.html
  content/articles/reverse-dns.md
  content/search.html
Labels: documentation
