Repository dnsimple/dnsimple-support, pull requests merged in 2024-06, with the labels that each got.

#1187 adding onboarding guides
  categories/dnsimple.yaml
  content/articles/guide-dashboard.md
  content/articles/guide-getting-started-with-your-team.md
  content/articles/guide-register-or-transfer-a-domain.md
  content/articles/guide-setup-and-delegate-zones.md
  content/files/add-zone-from-dashboard.png
  content/files/add-zone-from-domains.png
  content/files/add-zone-modal.png
Labels: documentation

#1191 Adding alt tags to all images with missing alts
  content/articles/dashboard.md
  content/articles/domain-list.md
  content/articles/domains-xxx.md
  content/articles/heroku-error-ssl.md
  content/articles/how-to-determine-certificate-authority.md
  content/articles/manage-a-record.md
  content/articles/manage-aaaa-record.md
  content/articles/manage-caa-record.md
  content/articles/manage-cname-record.md
  content/articles/manage-ds-record.md
  content/articles/manage-url-record.md
  content/articles/multi-factor-authentication.md
  content/articles/ssl-certificates-email-validation.md
  content/articles/ssl-certificates-types.md
  content/articles/transferring-domain-between-accounts.md
Labels: copy editing

#1189 Updates to changing email article
  content/articles/changing-email.md
  content/files/account-email.png
  content/files/account-menu.png
Labels: documentation

#1175 Document integrated DNS provider management improvements
  content/articles/integrated-dns-provider-amazon-route53.md
  content/articles/integrated-dns-provider-azure-dns.md
  content/articles/integrated-dns-provider-coredns.md
  content/articles/integrated-dns-providers.md
  content/articles/managing-integrated-zones.md
  content/files/account-external-provider-link-credentials.png
  content/files/account-integrated-dns-provider-connect-add-zones.png
  content/files/account-integrated-provider-add-remove-zones.png
  content/files/account-integrated-provider-link.png
  content/files/account-integrated-provider-manage-integrated-zones.png
  content/files/account-integrated-provider-unlink.png
  content/files/account-integrated-provider-view-zones.png
  content/files/account-integrated-providers.png
  content/files/dns-zone-providers-add-to-linked-provider.png
  content/files/dns-zone-providers-add-to-unlinked-provider.png
  content/files/dns-zone-providers-add-zone.png
  content/files/dns-zone-providers-delete-zone.png
  content/files/dns-zone-providers-delete.png
  content/files/dns-zone-providers-remove-zone-confirmation.png
  content/files/dns-zone-providers-remove.png
  content/files/integrated-dns-provider-azure.png
Labels: documentation

#1207 Removes Google Universal Analytics and Google Optimize configuration
  layouts/analytics.html
  nanoc.yaml
Labels: task

#1208 Updates to shared domains
  content/articles/sharing-domain.md
  content/files/shared-domain-accept.png
  content/files/shared-domain-dashboard-alert.png
Labels: documentation
