Repository dnsimple/dnsimple-support, pull requests merged in 2024-09, with the labels that each got.

#1240 Fixes searching for 'Record Editor'
  templates/search.js.erb
Labels: javascript

#1232 Final Critical Updates - Account Section
  content/articles/domain-access-control.md
  content/articles/google-identity-provider.md
  content/articles/multi-factor-authentication-enforcement.md
  content/articles/multi-factor-authentication.md
  content/articles/okta-identity-provider.md
  content/files/access-per-domain.png
  content/files/account-settings.png
  content/files/add-identity-provider.png
  content/files/identity-provider-list.png
  content/files/invite-with-limited-access.png
  content/files/limited-access-team-member.png
  content/files/manage-access.png
  content/files/mfa-disable.png
  content/files/mfa.png
  content/files/non-compliant-mfa-users.png
  content/files/remove-google-identity-success.png
  content/files/roles-per-domain.png
  content/files/team-member-access.png
  content/files/unlink-google-identity-provider.png
Labels: help wanted

#1242 Updating the excerpt for dig article
  content/articles/how-dig.md
Labels: articles

#1247 Update NOMINET .UK IPS-TAG documentation
  content/articles/domains-uk.md
Labels: documentation

#1248 Update Google IDP screenshots
  content/articles/google-identity-provider.md
  content/files/unlink-google-workspace-success.png
Labels: documentation

#1250 Add article about exporting domain names to file
  categories/domains.yaml
  content/articles/export-domain-names-to-file.md
  content/files/export-domain-names-to-file.png
Labels: articles

#1260 Bump webrick version
  Gemfile.lock
Labels: dependencies

#1256 Improving DNS Resolution Visibility: Add article about verifying domain resolution
  categories/domains.yaml
  content/articles/verifying-domain-resolution.md
  content/files/verifying-domain-resolution-notification.png
Labels: articles
