Repository dnsimple/dnsimple-support, pull requests merged in 2024-02, with the labels that each got.

#1133 Add dependabot instructions to update JS files
  .github/dependabot.yml
Labels: site-generator

#1146 Promoting CAA article from the blog
  content/index.html
Labels: copy editing

#1149 Add domain restore docs
  categories/domains.yaml
  content/articles/domains-au.md
  content/articles/domains-ch.md
  content/articles/domains-es.md
  content/articles/domains-li.md
  content/articles/restoring-domain.md
  content/articles/what-happens-when-domain-expires.md
  content/files/restore-domain-form.png
  content/files/restore-domain.png
Labels: documentation, copy editing
