Repository dnsimple/dnsimple-support, pull requests merged in 2025-02, with the labels that each got.

#1363 Adding the new video to diff between record types
  content/articles/differences-between-a-cname-alias-url.md
  content/assets/css/_typography.scss
Labels: documentation

#1364 We had to republish the video, thus update the embed key
  content/articles/differences-between-a-cname-alias-url.md
Labels: documentation

#1330 Bring the support widget to the support site
  .babelrc
  _widget/.gitignore
  _widget/README.md
  _widget/index.html
  _widget/src/assets/svgs.js
  _widget/src/components/app/component.vue
  _widget/src/components/app/reset.scss
  _widget/src/components/app/style.scss
  _widget/src/components/app/url-dictionary.js
  _widget/src/components/app/variables.scss
  _widget/src/components/article/component.vue
  _widget/src/components/article/resolving.scss
  _widget/src/components/article/style.scss
  _widget/src/components/article/syntax.scss
  _widget/src/components/article/tables.scss
  _widget/src/components/articles/component.vue
  _widget/src/components/articles/style.scss
  _widget/src/components/footer/component.vue
  _widget/src/components/footer/style.scss
  _widget/src/components/header/component.vue
  _widget/src/components/header/style.scss
  _widget/src/components/prompt/animate.scss
  _widget/src/components/prompt/component.vue
  _widget/src/components/prompt/style.scss
  _widget/src/components/welcome/component.vue
  _widget/src/components/welcome/style.scss
  _widget/src/main.js
  _widget/vite.config.js
  _widget/yarn.lock
  jest.config.js
  package.json
  spec/_widget/components/app.spec.js
  spec/_widget/components/article.spec.js
  spec/_widget/components/articles.spec.js
  spec/utils/styleMock.js
  yarn.lock
Labels: javascript

#1365 Improving Search Experience: Show "Getting Started" if empty query with no history
  _widget/src/components/app/component.vue
  _widget/src/components/getting-started/component.vue
  _widget/src/components/getting-started/style.scss
Labels: javascript

#1331 Trigger to open the support widget
  _widget/index.html
  _widget/src/assets/svgs.js
  _widget/src/components/app/component.vue
  _widget/src/components/app/reset.scss
  _widget/src/components/app/style.scss
  _widget/src/components/article/component.vue
  _widget/src/components/articles/component.vue
  _widget/src/components/articles/style.scss
  _widget/src/components/header/component.vue
  _widget/src/components/header/style.scss
  _widget/src/components/welcome/style.scss
  _widget/src/main.js
  content/assets/css/_template.scss
  content/search/results.js
  layouts/default.html
  package.json
  spec/_widget/components/app.spec.js
  spec/search/results.spec.js
  src/index.js
  templates/search.js.erb
Labels: javascript

#1369 Search: "Getting started" driven by article
  _widget/src/components/app/component.vue
  _widget/src/components/article/component.vue
  _widget/src/components/getting-started/component.vue
  _widget/src/components/getting-started/style.scss
  spec/_widget/components/app.spec.js
  spec/_widget/components/article.spec.js
Labels: javascript

#1368 Update SG domains registration documentation
  content/articles/domains-sg.md
Labels: documentation, copy editing

#1370 Search: Move `search.js` to the `js` world
  _widget/src/components/app/component.vue
  _widget/src/components/app/search.js
  _widget/src/components/article/component.vue
  _widget/src/components/article/style.scss
  lib/search.rb
  netlify.toml
  spec/_widget/components/app.spec.js
  spec/_widget/components/article.spec.js
  spec/_widget/components/search.spec.js
  spec/search/index.spec.js
  templates/dictionary.json.erb
Labels: javascript

#1372 Improving Search Experience: Use Posthog to track search queries and results
  _widget/src/components/app/analytics.js
  _widget/src/components/app/search.js
  spec/_widget/components/analytics.spec.js
  spec/_widget/components/search.spec.js
Labels: javascript

#1378 Improving Search Experience: ⌘K to open, Esc to close the support widget
  _widget/src/components/app/component.vue
  layouts/default.html
  spec/_widget/components/app.spec.js
Labels: javascript

#1371 Search: Improve results
  _widget/src/components/app/component.vue
  _widget/src/components/app/dictionary.js
  _widget/src/components/app/search.js
  _widget/src/components/article/style.scss
  package.json
  spec/_widget/components/app.spec.js
  spec/_widget/components/search.spec.js
Labels: javascript

#1379 Improving Search Experience: Keyboard shortcuts for support widget article navigation
  _widget/src/components/app/component.vue
  _widget/src/components/articles/component.vue
  _widget/src/components/articles/style.scss
  spec/_widget/components/app.spec.js
Labels: javascript

#1383 Improving Search Experience: Improve widget article navigation scrolling
  _widget/src/components/app/component.vue
Labels: javascript

#1384 Fix: Ignore when widget body is not found
  _widget/src/components/app/component.vue
Labels: javascript

#1382 Search: Relative links in an article on the same site should open via browser
  _widget/src/components/app/search.js
  _widget/src/components/article/component.vue
  spec/_widget/components/app.spec.js
  spec/_widget/components/article.spec.js
  spec/_widget/components/search.spec.js
Labels: javascript

#1385 Search: Add QVO to the dictionary
  _widget/src/components/app/dictionary.js
  spec/_widget/components/search.spec.js
Labels: javascript

#1389 Improving Search Experience: Add category headings to widget
  _widget/src/components/app/component.vue
  _widget/src/components/articles/component.vue
  _widget/src/components/articles/style.scss
  spec/_widget/components/app.spec.js
Labels: javascript

#1348 Critical updates to Services articles
  content/articles/atmail-service.md
  content/articles/fastmail-service.md
  content/articles/mailgun-service.md
  content/articles/squarespace-service.md
  content/articles/tender-service.md
Labels: documentation, help wanted

#1358 Finishing critical edits
  categories/account.yaml
  categories/api.yaml
  categories/templates.yaml
  content/articles/api-access-token.md
  content/articles/forgot-password.md
  content/articles/github-pages.md
  content/articles/oauth-applications.md
  content/articles/services.md
  content/articles/templates.md
  content/articles/webhooks.md
  content/files/access-token-generate.png
  content/files/access-token-new.png
  content/files/access-tokens-link.png
  content/files/access-tokens-new.png
  content/files/access-tokens.png
  content/files/app-created.png
  content/files/app-details.png
  content/files/delete-application-confirm.png
  content/files/delete-application.png
  content/files/forgot-password-link.png
  content/files/login-forgot-password.png
  content/files/new-application.png
  content/files/oauth-app-add.png
  content/files/oauth-app-created.png
  content/files/oauth-app-delete-confirm.png
  content/files/oauth-app-delete.png
  content/files/oauth-app-new.png
  content/files/oauth-app-revoke-tokens.png
  content/files/oauth-location.png
  content/files/revoke-all-user-tokens.png
  content/files/services-dns-page-manage.png
  content/files/services-list-remove.png
  content/files/services-list.png
  content/files/services-manage.png
  content/files/services-remove.png
  content/files/template-list.png
  content/files/template-main-page.png
  content/files/template-manage-dns.png
  content/files/template-records.png
  content/files/templates-tab.png
  content/files/webhook-delete.png
  content/files/webhooks-add-recipient.png
  content/files/webhooks-delete-recipient.png
  content/files/webhooks-link.png
  content/files/webhooks-list.png
  content/files/webhooks-listing.png
  content/files/webhooks-recipient-added.png
Labels: documentation, help wanted

#1387 Search: Clean up some build/test warnings
  _widget/yarn.lock
  eslint.config.js
  jest.config.js
  package.json
  webpack.config.cjs
  yarn.lock
Labels: javascript

#1386 Search: Add an error state when remote data is unable to be loaded
  _widget/src/components/app/component.vue
  _widget/src/components/article/component.vue
  _widget/src/components/articles/component.vue
  _widget/src/components/articles/style.scss
  spec/_widget/components/app.spec.js
Labels: javascript

#1390 Improving Search Experience: Prioritize current site results
  _widget/src/components/articles/component.vue
  spec/_widget/components/app.spec.js
Labels: javascript

#1394 Search: Better results for record notes
  _widget/src/components/app/dictionary.js
  spec/_widget/components/search.spec.js
Labels: javascript

#1396 Add excerpt for Resolving With article
  content/articles/resolving-with-us.html
Labels: documentation

#1391 Improving Search Experience: Recently visited articles
  _widget/src/components/app/component.vue
  _widget/src/components/articles/component.vue
  spec/_widget/components/app.spec.js
Labels: javascript

#1395 Search: Better results for partial matches
  _widget/src/components/app/component.vue
  _widget/src/components/app/dictionary.js
  _widget/src/components/app/search.js
  spec/_widget/components/article.spec.js
  spec/_widget/components/search.spec.js
Labels: javascript

#1398 Adding SAN YouTube video
  content/articles/what-is-ssl-san.md
Labels: copy editing

#1399 Search: Initialization specs
  _widget/src/components/app/component.vue
  _widget/src/components/app/search.js
  _widget/src/components/article/component.vue
  _widget/src/components/articles/component.vue
  _widget/src/components/prompt/component.vue
  _widget/src/initialize.js
  _widget/src/main.js
  spec/_widget/components/app.spec.js
  spec/_widget/components/article.spec.js
  spec/_widget/components/initialize.spec.js
Labels: javascript

#1400 Search: Refine the button
  content/assets/css/_template.scss
  layouts/default.html
Labels: javascript

#1401 Improving Search Experience: Store recently visited even when outside support widget
  _widget/src/main.js
  _widget/src/recently-visited.js
  spec/_widget/components/recently-visited.spec.js
Labels: javascript

#1397 Adding marketing banner capabilities for the support site
  banners.yml
  content/assets/css/_template.scss
  layouts/banner.html
  layouts/default.html
  lib/default.rb
Labels: site-generator

#1404 Improving Search Experience: Prioritize same-site results
  _widget/src/components/app/component.vue
  _widget/src/components/app/search.js
  spec/_widget/components/search.spec.js
Labels: javascript

#1403 Search: Dark
  _widget/src/components/app/component.vue
  _widget/src/components/app/style.scss
  _widget/src/components/app/variables.scss
  _widget/src/components/article/component.vue
  _widget/src/components/article/style.scss
  _widget/src/components/article/tables.scss
  _widget/src/components/articles/component.vue
  _widget/src/components/articles/style.scss
  _widget/src/components/footer/component.vue
  _widget/src/components/footer/style.scss
  _widget/src/components/header/component.vue
  _widget/src/components/header/style.scss
  _widget/src/components/prompt/style.scss
  _widget/src/components/welcome/style.scss
  spec/_widget/components/app.spec.js
Labels: javascript

#1407 Improve results for `domain validation`
  _widget/src/components/app/dictionary.js
  spec/_widget/components/search.spec.js
Labels: javascript

#1409 Search: QA feedback
  _widget/src/components/app/component.vue
  _widget/src/components/article/style.scss
  _widget/src/components/articles/component.vue
  _widget/src/components/articles/style.scss
  _widget/src/components/footer/style.scss
  _widget/src/components/header/style.scss
Labels: javascript

#1410 Add Digital Wallet to payment methods page
  content/articles/payment-methods.md
Labels: documentation

#1411 Add Wallet Replenishment page
  content/articles/wallet-replenishment.md
  content/files/add-funds-confirm.png
  content/files/add-funds-form.png
  content/files/wallet-card.png
Labels: documentation
