Repository dnsimple/dnsimple-support, pull requests merged in 2025-05, with the labels that each got.

#1457 Update docs for CAA records
  content/articles/caa-record.md
  content/articles/integrated-dns-provider-coredns.md
  content/files/record-caa-create-new.png
Labels: documentation

#1480 Add .ZA domains support article
  categories/domains.yaml
  content/articles/domains-za.md
Labels: documentation

#1484 Create account-multi-enterprise.md
  categories/account.yaml
  content/articles/account-multi-enterprise.md
  content/files/multi-account-contact.png
Labels: documentation, help wanted

#1488 Announcement: Deprecation of NS2 and NS4 legacy edge IPs
  content/articles/announcement-ns2-ns4-ip-addresses.md
Labels: documentation

#1482 Improve Account Switching: Support doc updates
  content/articles/account-invoice-history.md
  content/articles/account-multi.md
  content/articles/account-subscription-balance.md
  content/articles/account-users.md
  content/articles/activity-tracking.md
  content/articles/adding-domain.md
  content/articles/adding-subdomain.md
  content/articles/billing-settings.md
  content/articles/cancel-subscription.md
  content/articles/changing-account-information.md
  content/articles/changing-email.md
  content/articles/changing-payment-details.md
  content/articles/changing-plans.md
  content/articles/close-account.md
  content/articles/deleting-domain.md
  content/articles/dns-hosting.md
  content/articles/dnsimple-and-handshake.md
  content/articles/domain-auto-renewal.md
  content/articles/domain-transfer.md
  content/articles/email-forwarding.md
  content/articles/guide-dashboard.md
  content/articles/integrated-dns-providers.md
  content/articles/managing-integrated-domains.md
  content/articles/multi-factor-authentication-enforcement.md
  content/articles/multi-factor-authentication.md
  content/articles/reactivate-subscription.md
  content/articles/renewing-domain.md
  content/articles/restoring-domain.md
  content/articles/transferring-domain-away.md
  content/articles/wallet-replenishment.md
  content/files/account-nav-link.png
  content/files/account-settings.png
  content/files/account-switcher.jpg
  content/files/add-a-domain.png
  content/files/add-button-dns-zone.png
  content/files/change-contact-1.png
  content/files/contact-change.png
  content/files/dashboard-account-cards.png
  content/files/domain-names-tab.png
  content/files/domains-domain-link.png
  content/files/filtering-by-labels.png
  content/files/multiple-accounts-nav.png
  content/files/new-contacts.png
  content/files/template-list.png
  content/files/user-settings-link.png
  content/files/user-settings-menu-item.png
  content/files/user-settings-menu.png
  content/files/zone-import-results.png
Labels: documentation

#1490 Search: Fix table of contents links
  _widget/src/components/app/component.vue
  _widget/src/components/article/component.vue
  spec/_widget/components/app.spec.js
Labels: javascript

#1491 Improve domain auto-renewals section
  content/articles/domain-auto-renewal.md
  content/files/icann-3rd-expiration-mail.png
Labels: documentation, copy editing

#1489 Add Zone Verification article
  categories/dns.yaml
  content/articles/zone-verification.md
Labels: documentation

#1495 Adding lazy loading to youtube embeds
  content/articles/a-record.md
  content/articles/aaaa-record.md
  content/articles/api-access-token.md
  content/articles/common-dns-records.md
  content/articles/dashboard.md
  content/articles/differences-between-a-cname-alias-url.md
  content/articles/domain-access-control.md
  content/articles/domain-list.md
  content/articles/getting-started-clickfunnels.md
  content/articles/guide-dashboard.md
  content/articles/heroku-connector.md
  content/articles/integrated-dns-provider-amazon-route53.md
  content/articles/integrated-dns-provider-coredns.md
  content/articles/integrated-domain-provider-godaddy.md
  content/articles/name-server-sets.md
  content/articles/netlify-connector.md
  content/articles/okta-identity-provider.md
  content/articles/record-notes.md
  content/articles/registering-domain.md
  content/articles/secondary-dns-dnsimple-as-secondary.md
  content/articles/setting-name-servers.md
  content/articles/terraform-provider.md
  content/articles/what-is-a-nameserver.md
  content/articles/what-is-ssl-san.md
  content/articles/what-is-ttl.md
  content/index.html
  layouts/default.html
Labels: site-generator

#1492 Add warning about deleting pkeys of SSL certs needed for HTTPS redirects
  content/articles/redirector.md
Labels: documentation

#1497 Adjust the scroll margin to show the section header
  content/assets/css/_typography.scss
Labels: task

#1377 Using DNSimple as a secondary DNS with a hidden primary
  categories/secondary_dns.yaml
  content/articles/secondary-dns-dnsimple-with-hidden-primary.md
  content/files/secondary-dns-record-sync.png
  spec/_widget/components/search.spec.js
Labels: documentation

#1503 Custom illustrations for what is DNS article
  content/articles/what-is-dns.md
  content/files/dns-components.png
  content/files/dns-components.svg
  content/files/dns-recursive-and-iterative.png
  content/files/dns-recursive-vs-iterative.svg
  content/files/dns-resolution-steps.png
  content/files/dns-resolution-steps.svg
Labels: task
