Repository dnsimple/dnsimple-support, pull requests merged in 2025-01, with the labels that each got.

#1315 Service Articles — Critical Updates 2
  content/articles/format-service.md
  content/articles/gigalixir-service.md
  content/articles/jimdo-service.md
  content/articles/platformsh-service.md
  content/articles/tumblr-service.md
  content/files/format-service-setup.png
  content/files/gigalixer-setup.png
  content/files/one-click-services.png
Labels: documentation, help wanted

#1337 Add CM domains page
  categories/domains.yaml
  content/articles/domains-cm.md
Labels: documentation

#1319 Critical Updates to Service Articles - 3
  categories/services.yaml
  content/articles/blogger-service.md
  content/articles/google-workspace-service.md
  content/articles/kickofflabs-service.md
  content/articles/launchrock-service.md
  content/articles/office-365-service.md
  content/files/add-one-click-service.png
Labels: documentation, help wanted

#1353 Adding a record video to article
  content/articles/a-record.md
  content/articles/getting-started-clickfunnels.md
  content/articles/secondary-dns-dnsimple-as-secondary.md
  content/articles/what-is-a-nameserver.md
  content/index.html
Labels: documentation

#1349 Critical Service Updates - 6
  content/articles/pobox-service.md
  content/articles/postmark-dmarc-service.md
  content/articles/postmark-service.md
  content/articles/rackspace-email-service.md
  content/articles/shopify-service.md
Labels: documentation, help wanted

#1359 Bump video up on the a-record page
  content/articles/a-record.md
Labels: documentation, copy editing

#1361 adding ahrefs analytics tracker
  layouts/analytics.html
  nanoc.yaml
Labels: site-generator
