Repository dnsimple/dnsimple-support, pull requests merged in 2025-04, with the labels that each got.

#1441 disabling banner as webinar has passed
  banners.yml
Labels: site-generator, copy editing

#1442 adding video for AAAA from YouTube
  content/articles/aaaa-record.md
Labels: documentation

#1444 Updating Meta for articles to the suggestions from Site Guru
  categories/meta.yaml
  content/articles/adding-domain.md
  content/articles/adding-subdomain.md
  content/articles/dashboard.md
  content/articles/deleting-domain.md
  content/articles/dns-query-limits.md
  content/articles/dnsimple-plans.md
  content/articles/domain-masking.md
  content/articles/drop-catching.md
  content/articles/dynamic-dns.md
  content/articles/protection-ddos.md
  content/articles/resolving-with-us.html
  content/articles/restoring-domain.md
  content/articles/srv-record.md
  content/articles/troubleshooting-email-forwarding-gmail.md
  content/articles/troubleshooting-redirects.md
  content/articles/understanding-invoice.md
  content/articles/wallet-replenishment.md
  content/articles/wordpress.md
  lib/categories.rb
Labels: copy editing

#1446 more meta updates generated from site guru
  categories/meta.yaml
  content/articles/changing-payment-details.md
  content/articles/dkim-record.md
  content/articles/dmarc-record.md
  content/articles/domain-transfer.md
  content/articles/getting-started-clickfunnels.md
  content/articles/google-identity-provider.md
  content/articles/okta-identity-provider.md
  content/articles/pointing-domain-to-dnsimple.md
  content/articles/registering-domain.md
  content/articles/renewing-domain.md
  content/articles/secondary-dnsimple.md
  content/articles/ssl-certificates.md
  content/articles/zone-ns-records.md
Labels: copy editing

#1449 Ignore modal key events when modal is not opened
  _widget/src/components/app/component.vue
  _widget/src/main.js
Labels: javascript

#1453 More meta updates
  content/articles/mx-record.md
  content/articles/ns-record.md
  content/articles/pool-record.md
  content/articles/url-record.md
  content/articles/what-is-ssl-certificate-chain.md
  content/articles/what-is-tld.md
  content/articles/what-is-whois-privacy.md
  content/articles/where-are-your-servers-located.md
Labels: copy editing

#1452 Fix alert icons
  content/assets/css/_application.scss
  content/assets/css/colorscheme.scss
Labels: task

#1456 More meta updates
  content/articles/cloudflare-ds-record.md
  content/articles/urlforward-service.md
  content/articles/verifying-domain-resolution.md
  content/articles/web-hosting.md
  content/articles/webflow-service.md
  content/articles/webhooks.md
  content/articles/weebly-service.md
  content/articles/what-happens-if-i-stop-paying.md
  content/articles/what-is-certificate-authority.md
  content/articles/what-is-ssl-root-certificate.md
Labels: copy editing

#1459 Meta Updates
  content/articles/account-subscription-balance.md
  content/articles/cancel-subscription.md
  content/articles/domain-resolution-issues.md
  content/articles/heroku-error-differentapp.md
  content/articles/heroku-error-nosuchapp.md
  content/articles/heroku-error-ssl.md
  content/articles/integrated-domain-provider-transfer-domain.md
  content/articles/transfer-account-ownership.md
  content/articles/transferring-domain-away.md
  content/articles/transferring-domain-between-accounts.md
  content/articles/tumblr-service.md
  content/articles/txt-record.md
Labels: copy editing

#1464 Dperrymorrow/meta updates 2
  content/articles/how-is-dnsimple-pronounced.md
  content/articles/shopify-service.md
  content/articles/soa-record.md
  content/articles/spf-record.md
  content/articles/squarespace-service.md
  content/articles/ssl-certificate-with-microsoft-iis.md
  content/articles/ssl-certificate-with-nginx.md
  content/articles/ssl-certificate-with-windows.md
  content/articles/standard-vs-letsencrypt.md
  content/articles/subscription-renewals.md
  content/articles/supadupa-service.md
  content/articles/supported-dns-records.md
  content/articles/surge-service.md
  content/articles/templates-with-srv-records.md
  content/articles/templates.md
  content/articles/tender-service.md
  content/articles/wordpress-service.md
Labels: copy editing

#1460 Adding what is a TTL support page
  categories/dns.yaml
  content/articles/what-is-ttl.md
  content/files/ttl-configure.png
  content/files/ttl-manage.png
  content/files/ttl-regions.png
Labels: documentation, copy editing

#1469 Updating title of SOA record
  content/articles/soa-record.md
Labels: copy editing

#1470 More meta updates
  categories/meta.yaml
  content/articles/account-securing.md
  content/articles/account-users.md
  content/articles/amazon-s3-service.md
  content/articles/atmail-service.md
  content/articles/blogger-service.md
  content/articles/changing-plans.md
  content/articles/cloudflare-service.md
  content/articles/dnsimple-support.md
  content/articles/domain-list.md
  content/articles/fanout-service.md
  content/articles/fastly-service.md
  content/articles/format-service.md
  content/articles/guide-dashboard.md
  content/articles/guide-register-or-transfer-a-domain.md
  content/articles/heroku-service.md
  content/articles/jimdo-service.md
  content/articles/pobox-service.md
  content/articles/reactivate-subscription.md
  content/articles/reasons-registering-domain.md
  content/articles/recovering-deleted-domain.md
  content/articles/secondary-dns-dnsimple-as-secondary.md
  content/articles/services.md
  content/articles/terraform-provider.md
  content/articles/vanity-nameservers.md
  content/articles/why-not-web-hosting.md
Labels: copy editing

#1463 Update support articles to include invoice filtering for enterprise customers
  content/articles/account-invoice-history.md
  content/articles/dnsimple-plans.md
  content/files/enterprise-invoice-filters.png
Labels: documentation

#1472 Meta updates
  content/articles/blackbell-service.md
  content/articles/dnsimple-and-handshake.md
  content/articles/fastmail-service.md
  content/articles/geniuslink-service.md
  content/articles/gigalixir-service.md
  content/articles/launchrock-service.md
  content/articles/mailgun-service.md
  content/articles/manage-a-record.md
  content/articles/managing-integrated-zones.md
  content/articles/netlify-service.md
  content/articles/postmark-dmarc-service.md
  content/articles/regional-records.md
Labels: copy editing

#1466 What is DNS article
  categories/dns.yaml
  content/articles/what-is-dns.md
  content/files/dns-components.svg
  content/files/dns-recursive-vs-iterative.svg
  content/files/dns-resolution-steps.svg
Labels: documentation

#1477 Updating meta from spreadsheet
  content/articles/aldryn-service.md
  content/articles/alias-record.md
  content/articles/amazon-lightsail-service.md
  content/articles/amazon-route-53-integration-demo.md
  content/articles/changing-account-information.md
  content/articles/changing-email.md
  content/articles/cname-record.md
  content/articles/dns-hosting.md
  content/articles/dnsimple-nameservers.md
  content/articles/domain-apex-heroku.md
  content/articles/integrated-dns-provider-amazon-route53.md
  content/articles/integrated-dns-provider-azure-dns.md
  content/articles/kickofflabs-service.md
  content/articles/manage-aaaa-record.md
  content/articles/manage-caa-record.md
  content/articles/manage-url-record.md
  content/articles/office-365-service.md
  content/articles/platformsh-service.md
  content/articles/postmark-service.md
  content/articles/record-notes.md
  content/articles/windows-azure-service.md
Labels: copy editing
