Repository dnsimple/dnsimple-support, pull requests merged in 2025-08, with the labels that each got.

#1547 Making the search widget specs more forgiving
  spec/_widget/components/search.spec.js
Labels: site-generator

#1562 Keyword updates to DNSSEC articles
  content/articles/dnssec-chain-of-trust.md
  content/articles/dnssec.md
  content/articles/what-is-dnssec.md
Labels: documentation, copy editing

#1571 Update Vanity Name Server Documentation
  categories/dns.yaml
  categories/name_servers.yaml
  content/articles/setting-name-servers.md
  content/articles/vanity-nameservers.md
  content/articles/what-are-glue-records.md
  content/articles/what-are-vanity-name-servers.md
  content/files/vanity-name-servers-card-disable.png
  content/files/vanity-name-servers-card-enable.png
  content/files/vanity-name-servers-card.png
  content/files/vanity-name-servers-confirm-enabled.png
  content/files/vanity-name-servers-delegate.png
  content/files/vanity-name-servers-disable-card.png
  content/files/vanity-name-servers-disable.png
  content/files/vanity-name-servers-other-domain.png
  content/files/vanity-name-servers-same-domain.png
  content/files/vanity-name-servers-stop-delegation.png
Labels: documentation

#1572 moving the video to the glue records article
  content/articles/setting-name-servers.md
  content/articles/what-are-glue-records.md
Labels: documentation
