Repository dnsimple/dnsimple-support, pull requests merged in 2025-07, with the labels that each got.

#1527 Create dnssec-chain-of-trust.md
  content/articles/dnssec-chain-of-trust.md
  spec/_widget/components/search.spec.js
Labels: documentation

#1537 Create what-are-ds-records.md
  categories/dnssec.yaml
  content/articles/what-are-ds-records.md
Labels: documentation

#1531 Create understanding-rrsets-rrsigs.md
  content/articles/understanding-rrsets-rrsigs.md
Labels: documentation

#1532 Create nsec-nsec3-records.md
  content/articles/nsec-nsec3-records.md
Labels: documentation

#1533 Update ds-records-changing-dns.md
  content/articles/ds-records-changing-dns.md
  content/files/delete-ds-record.png
Labels: documentation

#1535 Create dnssec-management-in-dnsimple.md
  categories/dnssec.yaml
  content/articles/dnssec-management-in-dnsimple.md
  content/files/dnssec-configure-domain-list.png
  content/files/dnssec-configure.png
  content/files/dnssec-delete-confirm.png
  content/files/dnssec-delete.png
  content/files/dnssec-disable-confirmation.png
  content/files/dnssec-ds-record-keys.png
  content/files/dnssec-ds-records-interactive.png
  content/files/dnssec-manage-ds-records-empty.png
  content/files/dnssec-manage-ds-records.png
  content/files/dnssec-per-domain.png
  content/files/dnssec-view-config.png
  spec/_widget/components/search.spec.js
Labels: documentation, help wanted

#1534 Update manage-ds-record.md
  categories/dns.yaml
  categories/dnssec.yaml
  content/articles/manage-ds-record.md
  content/files/ds-records-manage.png
Labels: documentation

#1529 Update support documentation for SPF record discontinuation
  content/articles/spf-record.md
  content/articles/txt-record.md
Labels: documentation

#1544 change number of providers
  content/articles/protection-ddos.md
Labels: documentation, task

#1558 Add DNSSEC Video to What is DNSSEC article
  content/articles/what-is-dnssec.md
Labels: documentation, task
